server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
      gateway:
        discovery:
          locator:
            enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
        routes:
           - id: cloud-payment-service # 路由的id,没有规定规则但要求唯一,建议配合服务名
           #匹配后提供服务的路由地址
#             uri: http://localhost:8001
             uri: lb://CLOUD-PAYMENT-SERVICE
             predicates:
               - Path=/payment/getPaymentById/** # 断言，路径相匹配的进行路由
           - id: cloud-payment-service2
             uri: lb://CLOUD-PAYMENT-SERVICE
             predicates:
               - Path=/payment/discovery/** #断言,路径相匹配的进行路由
               - After=2020-06-05T16:57:57.086+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka
      register-with-eureka: true
      #抓取已有注册的信息 单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true



