server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-provider-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment-hystrix-8001
    prefer-ip-address: true